"""Update models

Revision ID: 39476571c5fa
Revises: c09e329d53a2
Create Date: 2023-05-14 14:57:12.845907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39476571c5fa'
down_revision = 'c09e329d53a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
